name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
    terraform:
      name: 'Terraform'
      env:
        creds: ${{ secrets.TERRAFORM_SECRETS }}
      runs-on: ubuntu-latest
      environment: dev

      defaults:
        run:
          shell: bash

      steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: 'erraform init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./terraform"

      - name: 'erraform validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./terraform"

      - name: 'erraform plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./terraform"

      - name: 'erraform apply'
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./terraform"
